{
 "title": "Internet connection",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Download",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Speedtest Ping",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Speedtest Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Speedtest Ping",
   "type": "timeseries",
   "description": "Speedtest Ping history",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "ICMP to 192.168.1.254",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=\"ping_icmp\", instance=\"192.168.1.254\"}",
     "legendFormat": "{{__name__}}, phase={{phase}}"
    }
   ]
  },
  {
   "title": "ICMP to 62.172.103.164",
   "type": "timeseries",
   "description": "ICMP time to Telehouse",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=\"ping_icmp\", instance=\"62.172.103.164\"}",
     "legendFormat": "{{__name__}}, phase={{phase}}"
    }
   ]
  },
  {
   "title": "ICMP to 8.8.8.8",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_icmp_duration_seconds{job=\"ping_icmp\", instance=\"8.8.8.8\"}",
     "legendFormat": "{{__name__}}, phase={{phase}}"
    }
   ]
  }
 ]
}